server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    userName: root
    password: viki
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    host: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
